//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatizacionResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int NoControl { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public Nullable<int> Semestre { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> NoProyecto { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public string Genero { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Proyecto_Residencia Proyecto_Residencia { get; set; }
    }
}
