//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatizacionResidencias
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ResidenciasEntities : DbContext
    {
        public ResidenciasEntities()
            : base("name=ResidenciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Asesor_Interno> Asesor_Interno { get; set; }
        public virtual DbSet<BitacoraTransacciones> BitacoraTransacciones { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<HorarioPresentacion> HorarioPresentacion { get; set; }
        public virtual DbSet<Params> Params { get; set; }
        public virtual DbSet<Proyecto_Residencia> Proyecto_Residencia { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int generarnip()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("generarnip");
        }
    }
}
