//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatizacionResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraTransacciones
    {
        public int IdTransaccion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Descripcion { get; set; }
        public string Campos { get; set; }
        public string ValoresOriginales { get; set; }
        public string ValoresNuevos { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> No_Proyecto { get; set; }
        public string Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
        public virtual Proyecto_Residencia Proyecto_Residencia { get; set; }
    }
}
