//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatizacionResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioPresentacion
    {
        public int IdPresentacion { get; set; }
        public Nullable<int> No_Proyecto { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Horainicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual Proyecto_Residencia Proyecto_Residencia { get; set; }
    }
}
